underdamped:	free_diffusion_underdamped_Langevin.c
		gcc -O3 free_diffusion_underdamped_Langevin.c -o underdamped.x -lm

overdamped:	free_diffusion_overdamped_Langevin.c
		gcc -O3 free_diffusion_overdamped_Langevin.c -o overdamped.x -lm
