overdamped:	overdamped_Langevin_oscillator.c
		gcc -O3 overdamped_Langevin_oscillator.c -o oscillator.x -lm

mod-overdamped:	modified_overdamped_Langevin_oscillator.c
		gcc -O3 modified_overdamped_Langevin_oscillator.c -o mod_oscillator.x -lm
